### ISSUE TITLE
The archive node request balance is 0

### ISSUE THREAD

**Issue by harveyff** [bnb-chain/bsc#1551]
Hi guys,

I am synchronizing an archive node, and it has just been synchronized for 1 day, but I found that when it queries the balance of historical blocks, it is always 0. This seems to be incorrect. Is it because my program is not started correctly? Or other reasons, thanks for your help.

System information
Geth version: geth version
1.1.23
OS & Version: Windows/Linux/OSX
Ubuntu 20.04.6 LTS (GNU/Linux 5.15.0-1033-aws x86_64)
Commit hash : (if develop)
in k8s

```
  containers:
        - name: bsc
          image: 'ghcr.io/bnb-chain/bsc:1.1.23'
          args:
            - '--syncmode=full'
            - '--gcmode=archive'
            - '--snapshot=false'
            - '--http'
            - '--cache=81920'
            - '--rpc.allow-unprotected-txs'
            - '--txlookuplimit=0'
            - '--http.corsdomain=*'
            - '--ws.origins=*'
```
The config file is downloaded from https://github.com/bnb-chain/bsc/releases/tag/v1.1.23.

```
 curl -XPOST --data '{"jsonrpc": "2.0", "id": 1, "method" : "eth_getBalance", "params": ["0x233aaa8e7b8c7297501f8576c2883f5a7c874e17", "0x493F2"]}' -H "Content-Type: Application/json" http://10.233.77.20:8545
```
{"jsonrpc":"2.0","id":1,"result":"0x0"}

```
curl -XPOST --data '{"jsonrpc": "2.0", "id": 1, "method" : "eth_getBalance", "params": ["0x233aaa8e7b8c7297501f8576c2883f5a7c874e17", "0x493F2"]}' -H "Content-Type: Application/json" https://fabled-quaint-patron.bsc.discover.quiknode.pro/xxx/
```
{"jsonrpc":"2.0","id":1,"result":"0x5d2ac2a306e0d000"}
