### ISSUE TITLE
V1.2.5 对磁盘IO的需求陡增？

### ISSUE THREAD

**Issue by bgdsh** [bnb-chain/bsc#1701]
我分别在几台机器上通过K8S部署了BSC的节点，但是升级到1.2.5之后，每天都会出现Pod因为磁盘压力导致被集群给停掉重新启动一个的情况。

```
status:
  message: 'Pod The node had condition: [DiskPressure]. '
  phase: Failed
  reason: Evicted
  startTime: '2023-06-14T18:15:26Z'
```
是否有其他人遇到了这个问题？
