### ISSUE TITLE
CPU consumption is too high during geth synchronization

### ISSUE THREAD

**Issue by AbelGate** [bnb-chain/bsc#1990]
When we upgrade the geth program from 1.2.11 to 1.2.13, sometimes we still find that the block height of the node lags behind the official height. The CPU usage of geth nodes is sometimes high and sometimes low. I don't know why this is happening. Please help me take a look, thank you.

The command line to start the program is：

`
geth --config /bsc/config/config.toml --datadir /bsc/node/ \
--cache 8000 --rpc.allow-unprotected-txs --txlookuplimit=0 \
--syncmode=full --tries-verify-mode=none --pruneancient=true \
--diffblock=5000 --ws --ws.addr 0.0.0.0 --maxpeers 200
`

hardware:

8 core CPU 2.70GHz 
32G RAM
1007G ssd hard drive

config.toml

```toml
[Eth]
NetworkId = 56
LightPeers = 100
UltraLightFraction = 75
TrieTimeout = 150000000000

[Eth.Miner]
GasCeil = 140000000
GasPrice = 3000000000
Recommit = 10000000000

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 3000000000
PriceBump = 10
AccountSlots = 200
GlobalSlots = 8000
AccountQueue = 200
GlobalQueue = 4000

[Eth.GPO]
Blocks = 20
Percentile = 60
OracleThreshold = 1000

[Node]
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
InsecureUnlockAllowed = false
HTTPPort = 8565
HTTPVirtualHosts = ["0.0.0.0"]
HTTPModules = ["eth", "net", "web3", "txpool", "parlia"]
WSPort = 8566
WSModules = ["net", "web3", "eth"]

[Node.P2P]
MaxPeers = 200
NoDiscovery = false
StaticNodes = []
ListenAddr = ":30311"
EnableMsgEvents = false
```

**Comment by STdevK** [comment]
Can you share more on the configuration setup and hardware specification?

**Comment by AbelGate** [comment]
hardware:

8 core CPU 2.70GHz 
32G RAM
1007G ssd hard drive

config.toml

```toml
[Eth]
NetworkId = 56
LightPeers = 100
UltraLightFraction = 75
TrieTimeout = 150000000000

[Eth.Miner]
GasCeil = 140000000
GasPrice = 3000000000
Recommit = 10000000000

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 3000000000
PriceBump = 10
AccountSlots = 200
GlobalSlots = 8000
AccountQueue = 200
GlobalQueue = 4000

[Eth.GPO]
Blocks = 20
Percentile = 60
OracleThreshold = 1000

[Node]
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
InsecureUnlockAllowed = false
HTTPPort = 8565
HTTPVirtualHosts = ["0.0.0.0"]
HTTPModules = ["eth", "net", "web3", "txpool", "parlia"]
WSPort = 8566
WSModules = ["net", "web3", "eth"]

[Node.P2P]
MaxPeers = 200
NoDiscovery = false
StaticNodes = []
ListenAddr = ":30311"
EnableMsgEvents = false
```
