### ISSUE TITLE
Fatal: Could not open database: open /bsc/node/geth/chaindata/ancient/chain/headers.cidx: no such file or directory

### ISSUE THREAD

**Issue by vaibhavraj05** [bnb-chain/bsc#1997]
i am trying to setup bsc node on my system with docker but i am facing issue 

1. first i downloaded the data from below website and with the given link 
`https://github.com/48Club/bsc-snapshots/tree/main#bsc-snapshots`
`https://snapshots.48.club/geth.fast.33660414.tar.zst`

I run the command 

```shell 
wget https://snapshots.48.club/geth.fast.33660414.tar.zst -O - | zstd -cd | tar xf -
```

and its download the `geth.fast/geth/chainnode` and `chaindata` contain all data 

2. Then i downloaded mainnet using below command provided on bsc website
```shell
wget   $(curl -s https://api.github.com/repos/bnb-chain/bsc/releases/latest |grep browser_ |grep mainnet |cut -d\" -f4)
unzip mainnet.zip
```
> And my folder structure look like this 
<img width="319" alt="image" src="https://github.com/bnb-chain/bsc-snapshots/assets/117675608/84c3951b-3043-4e9f-ab0e-fcd87c6453ee">

3. below is my docker compose

```yaml
version: "3.3"
services: 
  bsc:
    image : ghcr.io/bnb-chain/bsc:latest
    container_name: bsc
    restart: always
    ports:
      - 8575:8575
    volumes:
      - /bsc/config:/bsc/config
      - /bsc/data/geth.fast:/bsc/node
    command: --http.addr 0.0.0.0 --http.port 8575 --http.vhosts '*' --verbosity 5
```

these are the logs for the docker compose 
<img width="1300" alt="image" src="https://github.com/bnb-chain/bsc-snapshots/assets/117675608/7b3d5072-6821-4564-8e2d-4133839b8438">

and while running this command in container 
`geth --datadir node init ./config/genesis.json `
getting below error 
<img width="937" alt="image" src="https://github.com/bnb-chain/bsc-snapshots/assets/117675608/328de90d-369d-4569-aab7-d4ee7acee1f7">

**Fatal: Could not open database: open /bsc/node/geth/chaindata/ancient/chain/headers.cidx: no such file or directory**

**Comment by weiihann** [comment]
It seems like the snapshot that you've downloaded is a fast node, which has the following flags (refer to [this link](https://github.com/48Club/bsc-snapshots#geth-fast-node)):
```
--history.transactions=0 --syncmode=full --tries-verify-mode=none --pruneancient=true --db.engine=pebble
```

The `--pruneancient` is the key flag, because it signifies that ancient data will be deleted. Hence, that's why the `no such file or directory` occurred.

Another reason is that you wouldn't need to do `geth --datadir node init ./config/genesis.json`, because you've already downloaded the snapshot.

To start the node, just run the node normally. But if you face the same issue again, it might be due to an existing bug which has been solved in this PR (https://github.com/bnb-chain/bsc/pull/1986).

**Comment by du5** [comment]
same as https://github.com/48Club/bsc-snapshots/issues/120

**Comment by vaibhavraj05** [comment]
How can now i verify that is working fine, while running below command its not started yet, or i am doing something wrong 
<img width="1337" alt="image" src="https://github.com/bnb-chain/bsc/assets/117675608/4b66ef0b-4bb8-454c-a0c4-60728d98cb5f">


Below is my updated docker compose file 
<img width="1343" alt="image" src="https://github.com/bnb-chain/bsc/assets/117675608/e4b349c7-d76d-4686-b430-dec84601128e">

```yaml
version: "3.3"

services: 
  bsc:
    image : ghcr.io/bnb-chain/bsc:latest
    container_name: bsc
    restart: always
    ports:
      - 8575:8575
    volumes:
      - /bsc/config:/bsc/config
      - /bsc/data/geth.fast:/bsc/node
    command: --http.addr 0.0.0.0 --http.port 8575 --http.vhosts '*' --verbosity 5 --history.transactions=0 --syncmode=full --tries-verify-mode=none --pruneancient=true --db.engine=pebble
```
    
Below are my docker compose logs 
    
    
<img width="1358" alt="image" src="https://github.com/bnb-chain/bsc/assets/117675608/15ef77e6-7088-49aa-88b4-f10e99f697a1">

**Comment by du5** [comment]
It is recommended to read your `config.toml`, it will tell you where the logs are

**Comment by vaibhavraj05** [comment]
> It is recommended to read your `config.toml`, it will tell you where the logs are

Here my congif.toml

```shell
cat config.toml 
```
```toml
[Eth]
NetworkId = 56
LightPeers = 100
TrieTimeout = 150000000000

[Eth.Miner]
GasCeil = 140000000
GasPrice = 3000000000
Recommit = 10000000000

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 3000000000
PriceBump = 10
AccountSlots = 200
GlobalSlots = 8000
AccountQueue = 200
GlobalQueue = 4000

[Eth.GPO]
Blocks = 20
Percentile = 60
OracleThreshold = 1000

[Node]
IPCPath = "geth.ipc"
HTTPHost = "localhost"
InsecureUnlockAllowed = false
HTTPPort = 8545
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["eth", "net", "web3", "txpool", "parlia"]
WSPort = 8546
WSModules = ["net", "web3", "eth"]

[Node.P2P]
MaxPeers = 200
NoDiscovery = false
StaticNodes = []
ListenAddr = ":30311"
EnableMsgEvents = false

[Node.LogConfig]
FilePath = "bsc.log"
MaxBytesSize = 10485760
Level = "info"
FileRoot = ""
```


here is the log of bsc.log file 
<img width="1453" alt="image" src="https://github.com/bnb-chain/bsc/assets/117675608/be687a82-60ac-4478-a229-d70645038eb7">

**Comment by vaibhavraj05** [comment]
> It is recommended to read your `config.toml`, it will tell you where the logs are


Here my congif.toml

```shell
cat config.toml 
```
```toml
[Eth]
NetworkId = 56
LightPeers = 100
TrieTimeout = 150000000000

[Eth.Miner]
GasCeil = 140000000
GasPrice = 3000000000
Recommit = 10000000000

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 3000000000
PriceBump = 10
AccountSlots = 200
GlobalSlots = 8000
AccountQueue = 200
GlobalQueue = 4000

[Eth.GPO]
Blocks = 20
Percentile = 60
OracleThreshold = 1000

[Node]
IPCPath = "geth.ipc"
HTTPHost = "localhost"
InsecureUnlockAllowed = false
HTTPPort = 8545
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["eth", "net", "web3", "txpool", "parlia"]
WSPort = 8546
WSModules = ["net", "web3", "eth"]

[Node.P2P]
MaxPeers = 200
NoDiscovery = false
StaticNodes = []
ListenAddr = ":30311"
EnableMsgEvents = false

[Node.LogConfig]
FilePath = "bsc.log"
MaxBytesSize = 10485760
Level = "info"
FileRoot = ""
```


here is the log of bsc.log file 
<img width="1161" alt="image" src="https://github.com/bnb-chain/bsc/assets/117675608/fc2b740e-dd27-4231-ad51-6c794d8b5ee4">
