### ISSUE TITLE
The block height of the node server lags behind the official

### ISSUE THREAD

**Issue by AbelGate** [bnb-chain/bsc#2046]
When I changed the `[Node] HTTPHost` configuration option in the `config.toml` file in the server from "localhost" to "0.0.0.0", I found the following changes:

The block height of the node server lags behind the official node. And the CPU of our node server will soar from 20% to 100%.

Below are some server logs I obtained. You can compare the difference in processing speed between the two configurations. We are using the same machine and the same program; we just modified the configuration options.

Set `localhost`

```log
t=2023-12-07T06:48:51+0000 lvl=info msg="Imported new chain segment"             blocks=1  txs=1256  mgas=44.837   elapsed=172.035ms mgasps=260.626 number=34,139,043 hash=0xf4726f1eee418ba10d0a4ccc57eeeac07b3dec84e40079b413b38b0a24aefe92 dirty="0.00 B"
t=2023-12-07T06:48:51+0000 lvl=info msg="Imported new chain segment"             blocks=1  txs=1002  mgas=33.957   elapsed=129.288ms mgasps=262.642 number=34,139,044 hash=0x442ffb6660a9000018e3c8d251b450c490a6795c4e2264db958ddaa3b77df82a dirty="0.00 B"
t=2023-12-07T06:48:51+0000 lvl=info msg="Imported new chain segment"             blocks=1  txs=1008  mgas=34.408   elapsed=64.769ms  mgasps=531.231 number=34,139,044 hash=0x00730b8dd9a1005ab3c0de116d01373b691d0e3b25562ab0aade31d559f0f25c dirty="0.00 B"
t=2023-12-07T06:48:51+0000 lvl=info msg="Imported new chain segment"             blocks=1  txs=690   mgas=24.224   elapsed=68.739ms  mgasps=352.410 number=34,139,045 hash=0x7dd90d4d96b86d83029d71b2a8ef7b7b2c852c91890886fa404c6aef9eecb26a dirty="0.00 B"
```

Set '0.0.0.0'

```log
t=2023-12-07T06:43:17+0000 lvl=info msg="Imported new chain segment"             blocks=2  txs=742  mgas=35.751 elapsed=13.832s     mgasps=2.585 number=34,138,866 hash=0xdc094422fa188eb957d9cb2b7b39e0d3af3d97ce2542319a2fd4f389e012a84d age=3m26s    dirty="0.00 B"
t=2023-12-07T06:43:27+0000 lvl=info msg="Imported new chain segment"             blocks=1  txs=665  mgas=32.496 elapsed=10.007s     mgasps=3.247 number=34,138,867 hash=0xf21d672d5b7ae90d070d4180b307dd4cbaf58823f71fd69a05a6af01c7492508 age=3m33s    dirty="0.00 B"
t=2023-12-07T06:43:37+0000 lvl=info msg="Imported new chain segment"             blocks=1  txs=565  mgas=23.384 elapsed=10.309s     mgasps=2.268 number=34,138,868 hash=0x701a9714795e90633642d50d188158a24c3ae3a64dc95bbed604b82347060a87 age=3m40s    dirty="0.00 B"
```

Obviously, when set to "localhost", the synchronization speed of the server will be very fast. Please tell me why this is?

System information
Geth version: geth 1.2.15
OS & Version: Linux

hw:
8 core CPU 2.70GHz
32G RAM
1007G ssd hard drive

config.toml

```toml
[Eth]
NetworkId = 56
LightPeers = 100
TrieTimeout = 150000000000

[Eth.Miner]
GasCeil = 140000000
GasPrice = 3000000000
Recommit = 10000000000

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 3000000000
PriceBump = 10
AccountSlots = 200
GlobalSlots = 8000
AccountQueue = 200
GlobalQueue = 4000

[Eth.GPO]
Blocks = 20
Percentile = 60
OracleThreshold = 1000

[Node]
IPCPath = "geth.ipc"
HTTPHost = "localhost"
InsecureUnlockAllowed = false
HTTPPort = 8565
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["eth", "net", "web3", "txpool", "parlia"]
WSPort = 8566
WSModules = ["net", "web3", "eth"]

[Node.P2P]
MaxPeers = 200
NoDiscovery = false
StaticNodes = []
ListenAddr = ":30311"
EnableMsgEvents = false

[Node.LogConfig]
FilePath = "bsc.log"
MaxBytesSize = 10485760
Level = "info"
FileRoot = ""


```
