### ISSUE TITLE
The bsc full node server stops synchronizing and needs to be restarted to recover. 1.3.7

### ISSUE THREAD

**Issue by AbelGate** [bnb-chain/bsc#2104]
Geth version: 
```
Geth
Version: 1.3.7
Git Commit: f28b98a9947b52816714f90326b2545b08606b1a
Git Commit Date: 20231219
Architecture: amd64
Go Version: go1.20.12
Operating System: linux
GOPATH=
GOROOT=/opt/hostedtoolcache/go/1.20.12/x64
```
OS & Version:Linux alpine VERSION_ID=3.17.6
Running full node.
Running bsc mainnet.
Snapshot: https://snapshots.48.club/geth.fast.34152285.tar.zst
Hardware configuration:  CPU 16 core, RAM 32G, HD 983 GiB

Server startup command

```bash
geth --config /bsc/config/config.toml --datadir /bsc/node/ \
--cache 8000 --rpc.allow-unprotected-txs --history.transactions=0 --syncmode=full --tries-verify-mode=none --diffblock=5000 --pruneancient=true --db.engine=pebble \
--ws --ws.addr 0.0.0.0 --maxpeers 200
```

config.toml

```toml
[Eth]
NetworkId = 56
LightPeers = 100
TrieTimeout = 150000000000

[Eth.Miner]
GasCeil = 140000000
GasPrice = 3000000000
Recommit = 10000000000

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 3000000000
PriceBump = 10
AccountSlots = 200
GlobalSlots = 8000
AccountQueue = 200
GlobalQueue = 4000

[Eth.GPO]
Blocks = 20
Percentile = 60
OracleThreshold = 1000

[Node]
IPCPath = "geth.ipc"
HTTPHost = "0.0.0.0"
InsecureUnlockAllowed = false
HTTPPort = 8545
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["eth", "net", "web3", "txpool", "parlia"]
WSPort = 8546
WSModules = ["net", "web3", "eth"]

[Node.P2P]
MaxPeers = 200
NoDiscovery = false
StaticNodes = []
ListenAddr = ":30311"
EnableMsgEvents = false

[Node.LogConfig]
FilePath = "bsc.log"
MaxBytesSize = 10485760
Level = "info"
FileRoot = ""


```

After the server has been running for a period of time, it is found that the server will stop synchronizing with the main chain. When I looked at the server's logs I found this:

```log
t=2023-12-23T03:46:09+0000 lvl=info msg="Current status"                         table_size=127 pending_size=0  db_size=1,318,367
t=2023-12-23T03:47:09+0000 lvl=info msg="Current status"                         table_size=127 pending_size=0  db_size=1,318,367
t=2023-12-23T03:48:09+0000 lvl=info msg="Current status"                         table_size=127 pending_size=0  db_size=1,318,367
t=2023-12-23T03:49:09+0000 lvl=info msg="Current status"                         table_size=127 pending_size=0  db_size=1,318,367
```

After I restarted the `geth` program, the progress continued to be synchronized.
