### ISSUE TITLE
Disabling file logging for Docker

### ISSUE THREAD

**Issue by tornadocontrib** [bnb-chain/bsc#2345]
Would be great if we could disable file logging & bring back logs to stdout

**Comment by du5** [comment]
你只需要简单的修改即可, 就像这样:

```
FROM base-image

RUN curl -L -o mainnet.zip https://github.com/bnb-chain/bsc/releases/download/v1.3.12/mainnet.zip \
    && unzip mainnet.zip \
    && sed -i '/Node.LogConfig/,$d' config.toml \
    && mv config.toml /root/

WORKDIR /root

ENTRYPOINT [ "geth", "--config=config.toml"]

```

```bash
docker run -d ........ image-name --http --http.port=114514 ......

```

```yaml

services:
  geth:
    image: image-name
    command: |
      --http
      --http.port=114514
      ....

```
