### ISSUE TITLE
bug: `the method txpool_inspect does not exist/is not available` error after RPC call on `fast node` instance

### ISSUE THREAD

**Issue by Aviksaikat** [bnb-chain/bsc#2743]
#### System information

Geth version: `geth version 1.4.15-ec318b9c-20240919`
OS & Version: `Linux`
Commit hash : (if `develop`)

#### Expected behaviour

Should return pending transaction.

#### Actual behaviour

```py
web3.exceptions.MethodUnavailable: {'code': -32601, 'message': 'the method txpool_inspect \
does not exist/is not available'}
```
![image](https://github.com/user-attachments/assets/fbf445f4-1da4-4356-b029-4f1addefed50)

#### Steps to reproduce the behaviour

1. Download the latest snapshot of the `fast node` from https://github.com/48Club/bsc-snapshots `v1.4.15`, `SHA256`: `ef7df48d901eaa294a93f0f658d740bf6da8d93d34f92fab1f77ee92d4da5f87`
2. Run `geth` with the following instance

```sh
geth --config $BSC_CONFIG --datadir $DATA_DIR --cache 8000 --rpc.allow-unprotected-txs \ 
--history.transactions 0 --tries-verify-mode none --state.scheme path --ws --ws.port 8555 \ 
--http.api "eth,net,web3,txpool" --ws.api "eth,net,web3,txpool"
```

`config.toml`

```toml
[Eth]
NetworkId = 56
LightPeers = 100
TrieTimeout = 150000000000

[Eth.Miner]
GasCeil = 140000000
GasPrice = 1000000000
Recommit = 10000000000

[Eth.TxPool]
Locals = []
NoLocals = true
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1000000000
PriceBump = 10
AccountSlots = 200
GlobalSlots = 8000
AccountQueue = 200
GlobalQueue = 4000

[Eth.GPO]
Blocks = 20
Percentile = 60
OracleThreshold = 1000

[Node]
IPCPath = "geth.ipc"
HTTPHost = "localhost"
InsecureUnlockAllowed = false
HTTPPort = 8545
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["eth", "net", "web3", "txpool", "parlia"]
WSPort = 8546
WSModules = ["net", "web3", "eth", "txpool", "parlia"]

[Node.P2P]
MaxPeers = 200
NoDiscovery = false
StaticNodes = []
ListenAddr = ":30311"
EnableMsgEvents = false

[Node.LogConfig]
FilePath = "bsc.log"
MaxBytesSize = 10485760
Level = "info"
FileRoot = ""
```

#### Backtrace

````sh
[...]
t=2024-10-25T06:04:16+0000 lvl=info msg="Imported new chain segment" number=3814449 hash=0xafa0bf0ea839c4200ce281251db427cd79730faaa7d1841f15625b96c183c68f miner=0x72b61c6014342d914470eC7aC2975bE345796c2b blocks=58 txs=1076 blobs=0 mgas=98.20805 elapsed=913.052ms mgasps=107.56015013684264 age=3y10mo5d snapdiffs="1.75 MiB" triedirty="0.00 B" trieimutabledirty="0.00 B"
t=2024-10-25T06:04:24+0000 lvl=info msg="Imported new chain segment" number=3814999 hash=0x712f25a12f64ba0c0f372e08ed80a735071ca1c0ab2ecfa39ac6593f6d539081 miner=0xa34EFE6222E33adB84307f41B218D1823AfB6F6D blocks=550 txs=7825 blobs=0 mgas=762.034422 elapsed=8.009s mgasps=95.14357913624241 age=3y10mo5d snapdiffs="4.08 MiB" triedirty="0.00 B" trieimutabledirty="0.00 B"
t=2024-10-25T06:04:32+0000 lvl=info msg="Imported new chain segment" number=3815552 hash=0x207c179600f740abd509a4a0c934bca49871cb6c8521469dfe0adf56e340633b miner=0xea0A6E3c511bbD10f4519EcE37Dc24887e11b55d blocks=553 txs=8045 blobs=0 mgas=747.529841 elapsed=8.005s mgasps=93.37499877149638 age=3y10mo5d snapdiffs="2.37 MiB" triedirty="0.00 B" trieimutabledirty="0.00 B"
t=2024-10-25T06:04:40+0000 lvl=info msg="Imported new chain segment" number=3816082 hash=0x21ddf101691c086172e34ba172ae7d6f7436b05c1d688b0d33a3145287fd94b8 miner=0x4430b3230294D12c6AB2aAC5C2cd68E80B16b581 blocks=530 txs=8224 blobs=0 mgas=768.29106 elapsed=8.006s mgasps=95.95800220458675 age=3y10mo5d snapdiffs="576.50 KiB" triedirty="0.00 B" trieimutabledirty="0.00 B"
t=2024-10-25T06:04:46+0000 lvl=info msg="Imported new chain segment" number=3816497 hash=0x49f6720d47fe79a5d5eff77f8f1ea9ddf998eb46c6c9db8253915d0359705e8f miner=0xea0A6E3c511bbD10f4519EcE37Dc24887e11b55d blocks=415 txs=5272 blobs=0 mgas=519.562681 elapsed=5.797s mgasps=89.61626998644104 age=3y10mo5d snapdiffs="2.15 MiB" triedirty="0.00 B" trieimutabledirty="0.00 B"
t=2024-10-25T06:04:54+0000 lvl=info msg="Imported new chain segment" number=3817044 hash=0xb62ad59feabd67797fcf94b152d26d4b32105832a10d457e5fc791e0ad2a081e miner=0x0BAC492386862aD3dF4B666Bc096b0505BB694Da blocks=547 txs=7646 blobs=0 mgas=762.687161 elapsed=8.005s mgasps=95.2693709050313 age=3y10mo5d snapdiffs="497.50 KiB" triedirty="0.00 B" trieimutabledirty="0.00 B"
t=2024-10-25T06:05:02+0000 lvl=info msg="Imported new chain segment" number=3817598 hash=0x99aede0a9a98a21820120e2b787f944b91ef52489e7209fd15b14c7ce3409d7a miner=0x6BBad7Cf34b5fA511d8e963dbba288B1960E75D6 blocks=554 txs=6945 blobs=0 mgas=670.076287 elapsed=8.004s mgasps=83.7091698986101 age=3y10mo5d snapdiffs="2.53 MiB" triedirty="0.00 B" trieimutabledirty="0.00 B"
t=2024-10-25T06:05:10+0000 lvl=info msg="Imported new chain segment" number=3818170 hash=0xbb7bc46dd297656bbe626208228c79bad073694071d72c635f4e43fb42a9a686 miner=0xa34EFE6222E33adB84307f41B218D1823AfB6F6D blocks=572 txs=7579 blobs=0 mgas=710.056562 elapsed=8.008s mgasps=88.66146105520286 age=3y10mo5d snapdiffs="551.80 KiB" triedirty="0.00 B" trieimutabledirty="0.00 B"
t=2024-10-25T06:05:15+0000 lvl=info msg="Imported new chain segment" number=3818545 hash=0xe2a932750e995bbf0cdeae2a15de11f92cc16340ba05ba778ef7a6f7891abf17 miner=0x7AE2F5B9e386cd1B50A4550696D957cB4900f03a blocks=375 txs=4381 blobs=0 mgas=437.066043 elapsed=5.081s mgasps=86.00930455888049 age=3y10mo5d snapdiffs="1.80 MiB" triedirty="0.00 B" trieimutabledirty="0.00 B"
t=2024-10-25T06:05:23+0000 lvl=info msg="Imported new chain segment" number=3819103 hash=0x3504de780caf340589055093df3fb47c8b223064b68375c692b8e89570da9823 miner=0x22B81f8E175FFde54d797FE11eB03F9E3BF75F1d blocks=558 txs=7515 blobs=0 mgas=738.804871 elapsed=8.000s mgasps=92.34190531568458 age=3y10mo5d snapdiffs="3.94 MiB" triedirty="0.00 B" trieimutabledirty="0.00 B"
t=2024-10-25T06:05:31+0000 lvl=info msg="Imported new chain segment" number=3819673 hash=0x935d0a94601c6de7e15d5fe582c02a169d10cf39823ded235036f210bcb3358a miner=0x4430b3230294D12c6AB2aAC5C2cd68E80B16b581 blocks=570 txs=7776 blobs=0 mgas=730.106863 elapsed=8.008s mgasps=91.16739175083327 age=3y10mo5d snapdiffs="2.04 MiB" triedirty="0.00 B" trieimutabledirty="0.00 B"
````

When submitting logs: please submit them as text and not screenshots.

**Comment by galaio** [comment]
It works fine on my node with fast node.
```bash
# ps -ax | grep bsc
./bsc --http --ws.port 8546 --tries-verify-mode none --syncmode full --ws.addr $IP --db.engine pebble --ws --datadir /server/data-seed/ --cache 2048 --pprof.addr 0.0.0.0 --metrics --rpc.allow-unprotected-txs --history.transactions 15768000 --pprof --http.corsdomain * --config /server/data-seed/config.toml
# curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"txpool_inspect","params":[],"id":83}' $IP:8545
{"jsonrpc":"2.0","id":83,"result":{"pending":{"0x454d5Dc8956C468111E3e31315Ac2b38b03Bf576":{"170783":"0xC8Cf9bAC05202A0e6527F2745D8d0adef7A6a8FE: 0 wei + 68782 gas × 200000000000 wei"}},"queued":{"0x00d69911Ce3FaA57ed09C862CC842415232C0dB7":{"97":"0x84956c596B6f9E48ec0749df6D22DfD8e571a42b: 0 wei + 92529 gas × 32333333333 wei","98":"0x84956c596B6f9E48ec0749df6D22DfD8e571a42b: 0 wei + 92529 gas × 4850000000 wei"},"0x00df7cb82a1D7438B1b9f500b47314419b438bDd":{"50":"0x00df7cb82a1D7438B1b9f500b47314419b438bDd: 0 wei + 77167 gas × 5500000000 wei",....}
```
And config.toml has:

```toml
[Node]
DataDir = "node"
InsecureUnlockAllowed = false
NoUSB = true
IPCPath = "geth.ipc"
HTTPHost = "10.201.41.47"
HTTPPort = 8545
HTTPVirtualHosts = ["*"]
HTTPModules = ["debug","eth", "net", "web3", "txpool", "parlia"]
WSPort = 8546
WSModules = ["net", "web3", "eth"]
```

could you try this cmd again?
```bash
curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"txpool_inspect","params":[],"id":83}' $IP:8545
```
